kind: pipeline
type: docker
name: default

steps:

- name: publish-image
  image: plugins/docker
  settings: 
    dockerfile: Dockerfile
    context: .
    registry: hub.codefirst.iut.uca.fr
    repo: hub.codefirst.iut.uca.fr/corentin.richard/babamaco
    username:
      from_secret: SECRET_REGISTRY_USERNAME
    password:
      from_secret: SECRET_REGISTRY_PASSWORD 


trigger:
  event:
    - push
    - pull_request